"""initial_with_parcelas

Revision ID: cfd8663aee73
Revises: 
Create Date: 2026-03-07 19:24:56.407458
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cfd8663aee73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transacoes', sa.Column('parcela_atual', sa.Integer(), nullable=True))
    op.add_column('transacoes', sa.Column('total_parcelas', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transacoes', 'total_parcelas')
    op.drop_column('transacoes', 'parcela_atual')
    # ### end Alembic commands ###
